In [1]:
import pandas as pd

In [2]:
from pd import DataFrame

ModuleNotFoundError: ignored

In [3]:
from pandas import DataFrame

In [4]:
DataFrame()

Empty DataFrame
Columns: []
Index: []

In [5]:
import pandas as pd

In [6]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [7]:
 import numpy as np

In [8]:
np.array

<function numpy.array>

In [10]:
a = np.array[[1,2,3],[1,2],[3,2]]


TypeError: ignored

In [11]:
import numpy as np

ndarrary 생성

In [12]:
arr = np.array([1,2,3,4], dtype=int)

In [13]:
arr

array([1, 2, 3, 4])

In [15]:
np.shape(arr)

(4,)

In [16]:
type(arr)

numpy.ndarray

In [18]:
mylist1 = [1,2,3,4]
mylist2 = [[1,2,3,4],[5,6,7,8]]

In [20]:
arr1 = np.array(mylist1)

In [21]:
arr2 = np.array(mylist2)

In [22]:
arr1

array([1, 2, 3, 4])

In [23]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
np.shape(arr2)

(2, 4)

In [26]:
mylist = [1, 3,14, '테디', '1234']

In [27]:
mylist

[1, 3, 14, '테디', '1234']

In [28]:
type(mylist)

list

In [29]:
arr = np.array(mylist)

In [30]:
arr

array(['1', '3', '14', '테디', '1234'], dtype='<U21')

In [31]:
arr1 = np.array(mylist, dtype=int)

ValueError: ignored