In [2]:
import numpy as np


In [3]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 7, 9])

In [4]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [5]:
np.sort(arr)[::-1]

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [6]:
arr2 = np.sort(arr)

In [7]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [8]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [9]:
arr.sort()

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [11]:
arr2d = np.array([[5, 6, 7, 8], 
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])

In [12]:
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [13]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [14]:
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [15]:
arr2d = np.array([[5, 6, 7, 8], 
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])

In [16]:
np.argsort(arr2d, axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]])

In [17]:
np.argsort(arr2d, axis=0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]])

In [18]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [19]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [20]:
a+b

array([[4, 6, 8],
       [3, 5, 7]])

In [21]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [22]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [23]:
a+b

ValueError: ignored

In [24]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [25]:
np.sum(a, axis=0)

array([3, 5, 7])

In [26]:
np.sum(a, axis=1)

array([6, 9])

In [28]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [29]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [30]:
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [31]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [32]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [33]:
a - b

ValueError: ignored

In [44]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [45]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [46]:
a.shape, b.shape

((2, 3), (2, 3))

In [47]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [48]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [49]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [50]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [63]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [64]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [65]:
a.shape, b.shape

((3, 3), (3, 2))

In [66]:
a*b

ValueError: ignored

In [67]:
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [55]:
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [56]:
1*1 + 2*3 + 3*5

22

In [57]:
1*2 + 2*4 + 3*6

28

In [68]:
b.dot(a)

ValueError: ignored

In [70]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [71]:
b = np.array([[3, 3, 3], 
              [3, 3, 3]])

In [72]:
a + b

array([[4, 5, 6],
       [5, 6, 7]])

In [73]:
a + 3

array([[4, 5, 6],
       [5, 6, 7]])

In [74]:
a - 3

array([[-2, -1,  0],
       [-1,  0,  1]])

In [75]:
a * 3

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [76]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])

In [77]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [78]:
b = np.array([[1], 
              [2]])

In [79]:
a.shape, b.shape

((2, 3), (2, 1))

In [80]:
a * b

array([[1, 2, 3],
       [4, 6, 8]])

In [81]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [82]:
b = np.array([1, 2, 3])

In [83]:
a * b

array([[ 1,  4,  9],
       [ 2,  6, 12]])