In [1]:
import numpy as np

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[0]

0

In [6]:
arr[4]

4

In [7]:
arr[-1]

9

In [8]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [9]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
arr2d[0]

array([1, 2, 3, 4])

In [11]:
arr2d[0:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
arr2d.shape

(3, 4)

In [13]:
arr2d[0,2]

3

In [14]:
arr[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[:5]

array([0, 1, 2, 3, 4])

In [16]:
arr[1:5]

array([1, 2, 3, 4])

In [17]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
arr[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
arr2d[0, 1:]

array([2, 3, 4])

In [20]:
arr2d[0, :-1]

array([1, 2, 3])

In [21]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

In [22]:
idx = [1, 3, 5]

In [23]:
arr[idx]

array([23,  7, 65])

In [24]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [25]:
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
arr2d[:-1, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
arr2d[0, 1]

2

In [30]:
arr2d[[0, 1,2], :]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr2d[[2], :]

array([[ 9, 10, 11, 12]])

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [33]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [34]:
myTrueFalse = [True, False, True]

In [35]:
arr[myTrueFalse]

IndexError: ignored

In [36]:
myTrueFalse = [True, False, True, False, True, False, True]

In [37]:
arr[myTrueFalse]

array([1, 3, 5, 7])

In [38]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
arr2d > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
arr2d[ arr2d > 2 ]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
arr1d = arr2d[ arr2d < 5 ]

TypeError: ignored

In [44]:
arr2d

[array([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])]

Arange

In [47]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [48]:
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [51]:
arr = np.arange(1, 11)

In [52]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr = np.arange(start=1, stop=11)

In [55]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr = np.arange(start=1, stop=1100)

In [57]:
arr

array([   1,    2,    3, ..., 1097, 1098, 1099])

In [58]:
arr1 = np.arange(stop=1100, start=1)

In [59]:
arr1

array([   1,    2,    3, ..., 1097, 1098, 1099])

In [60]:
arr = np.arange(1, 11, 2)

In [61]:
arr

array([1, 3, 5, 7, 9])

In [62]:
arr1 = np.arange(start=1, stop=11, step=2)

In [63]:
arr1

array([1, 3, 5, 7, 9])

In [64]:
arr = np.arange(1, 11)

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [67]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [68]:
for i in range(1, 11, 2):
    print(i)

1
3
5
7
9
