In [2]:
import numpy as np
import pandas as pd

In [4]:
arr = np.random.randn(5, 4)

In [5]:
arr.mean()

0.13702824632604607

In [6]:
np.mean(arr)

0.13702824632604607

In [7]:
arr = np.random.randn(5, 3)

In [8]:
arr

array([[-0.4038337 , -0.01999851,  0.6360574 ],
       [ 0.07311326,  1.39057886,  0.78697924],
       [ 0.02476209,  0.73140536, -1.51310401],
       [-0.45487169,  1.42054795, -0.49230215],
       [ 1.74821807,  0.06551054,  0.05110508]])

In [9]:
arr.sort(1)

In [10]:
arr

array([[-0.4038337 , -0.01999851,  0.6360574 ],
       [ 0.07311326,  0.78697924,  1.39057886],
       [-1.51310401,  0.02476209,  0.73140536],
       [-0.49230215, -0.45487169,  1.42054795],
       [ 0.05110508,  0.06551054,  1.74821807]])

In [11]:
large_arr = np.random.randn(1000)

In [12]:
large_arr.sort()

In [13]:
large_arr

array([-2.66126455e+00, -2.63919584e+00, -2.59448139e+00, -2.56611047e+00,
       -2.48716372e+00, -2.45943988e+00, -2.45444762e+00, -2.45326214e+00,
       -2.41830824e+00, -2.37416948e+00, -2.34580135e+00, -2.32436223e+00,
       -2.27673853e+00, -2.25423856e+00, -2.15943304e+00, -2.14357325e+00,
       -2.13497070e+00, -2.11495899e+00, -2.10758916e+00, -2.09939200e+00,
       -2.08679117e+00, -2.07002076e+00, -2.02583245e+00, -2.01164133e+00,
       -2.00827947e+00, -1.99671510e+00, -1.99261656e+00, -1.98143602e+00,
       -1.97910865e+00, -1.97574792e+00, -1.97042157e+00, -1.96690774e+00,
       -1.93192803e+00, -1.88365186e+00, -1.87033092e+00, -1.85828205e+00,
       -1.82356510e+00, -1.81731296e+00, -1.80709958e+00, -1.80498450e+00,
       -1.79327239e+00, -1.77329542e+00, -1.76018174e+00, -1.74925475e+00,
       -1.74267256e+00, -1.73421453e+00, -1.70149700e+00, -1.67725591e+00,
       -1.67169389e+00, -1.67138643e+00, -1.65640285e+00, -1.65443068e+00,
       -1.63503201e+00, -

In [14]:
large_arr[int(0.05 * len(large_arr))]

-1.6564028527192853

In [15]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [16]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [18]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [19]:
ints

array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [21]:
np.unique(ints)

array([1, 2, 3, 4])

In [22]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [23]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [24]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [25]:
arr = np.arange(10)

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.save('some_array', arr)

In [28]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.savez('array+archive.npz', a=arr, b=arr)

In [31]:
arch = np.load('array_archive.npz')

FileNotFoundError: [Errno 2] No such file or directory: 'array_archive.npz'

In [32]:
!cat array_ex.txt

'cat'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [33]:
x = np.array([[1., 2., 3.], [4., 5., 6]])

In [34]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [35]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [36]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [37]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [38]:
from numpy.linalg import inv, qr

In [39]:
X = np.random.randn(5, 5)

In [40]:
mat = X.T.dot(X)

In [41]:
inv(mat)

array([[ 6.34656542, -5.76781469, -0.57073778,  3.91972407, -1.15718449],
       [-5.76781469,  5.86597621,  0.40423506, -3.95363861,  1.26217897],
       [-0.57073778,  0.40423506,  0.50738802, -0.22495311,  0.08403882],
       [ 3.91972407, -3.95363861, -0.22495311,  2.81415868, -0.86438467],
       [-1.15718449,  1.26217897,  0.08403882, -0.86438467,  0.49237274]])

In [42]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  7.14286592e-16,  2.17881568e-17,
         3.46221642e-16,  1.50239547e-16],
       [-1.69737124e-16,  1.00000000e+00,  3.01224210e-16,
         1.44230716e-15, -7.00351205e-16],
       [-5.97577611e-17,  4.13646162e-16,  1.00000000e+00,
        -6.18842328e-16,  2.65081976e-16],
       [ 5.41331954e-17,  2.65831024e-15,  3.33283535e-16,
         1.00000000e+00, -3.21121217e-16],
       [ 7.73261113e-16,  3.10442704e-16, -1.18759478e-17,
         2.40448614e-16,  1.00000000e+00]])

In [43]:
q, r = qr(mat)

In [44]:
r

array([[-2.56915709, -2.73272854, -1.46254874,  0.56773021,  2.77434447],
       [ 0.        , -5.83532059,  1.18530144, -8.27196024,  0.40800449],
       [ 0.        ,  0.        , -1.968136  , -0.28389921, -0.17031392],
       [ 0.        ,  0.        ,  0.        , -1.33985555, -4.22984199],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.50450863]])

#### ????

In [46]:
samples = np.random.normal(size = (4, 4))

In [48]:
samples

array([[ 0.63492826,  0.8965247 , -0.10392162,  2.05216223],
       [-1.59562814, -0.26531221, -0.77089811,  2.98519596],
       [ 0.02387611,  0.76478597,  1.38125945, -0.80367684],
       [ 3.26098666, -0.64154927, -0.72690246,  1.69541883]])

In [49]:
from random import normalvariate

In [50]:
N = 1000000

In [54]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

793 ms ± 21.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [55]:
%timeit np.random.normal(size = N)

26.4 ms ± 340 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 계단 오르내리기 예제...

In [58]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

#### xrange는 range로 대체...

In [59]:
nsteps = 1000
draws = np.random.randint(0, 2, size = nsteps)

In [60]:
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [62]:
walk.min()

-11

In [64]:
walk.max()

57

In [66]:
(np.abs(walk) >= 10).argmax()

91

In [67]:
nwalks = 5000

In [68]:
nsteps = 1000

In [69]:
draws = np.random.randint(0, 2, size=(nwalks, nsteps))

In [71]:
steps = np.where(draws > 0, 1, -1)

In [72]:
walks = steps.cumsum(1)

In [75]:
walks

array([[  1,   2,   3, ..., -28, -29, -28],
       [ -1,   0,  -1, ..., -16, -17, -16],
       [  1,   0,   1, ...,   6,   5,   4],
       ...,
       [ -1,  -2,  -3, ...,  16,  17,  16],
       [  1,   0,  -1, ...,   6,   7,   8],
       [  1,   2,   3, ...,  -2,  -3,  -2]], dtype=int32)

In [76]:
walks.max()

117

In [77]:
walks.min()

-127

In [78]:
hits30 = (np.abs(walks) >= 30).any(1)

In [79]:
hits30

array([ True,  True, False, ...,  True, False, False])

In [80]:
hits30.sum()

3416

In [81]:
crossing_times = (np.abs(walks[hits30]) >=  30).argmax(1)

In [82]:
crossing_times.mean()

508.0140515222482

In [83]:
steps = np.random.normal(loc = 0, scale = 0.25, size=(nwalks, nsteps))

In [84]:
steps

array([[-0.11413246, -0.2122693 ,  0.26045629, ...,  0.20757263,
        -0.29850425, -0.09833529],
       [ 0.25047963, -0.06539353, -0.02165222, ..., -0.03254668,
        -0.21545774,  0.22536338],
       [-0.54041387, -0.27063552, -0.04816532, ...,  0.21488985,
        -0.49399061,  0.30623142],
       ...,
       [-0.11111862,  0.13236029,  0.31823994, ...,  0.31667012,
        -0.31438153, -0.21156274],
       [ 0.00260664, -0.26712147, -0.1636725 , ...,  0.03222724,
        -0.03425713,  0.04163126],
       [-0.09029324, -0.01887281,  0.18649466, ..., -0.67995099,
         0.05177016, -0.42429779]])