In [1]:
import json

In [2]:
path = 'ch-2/usagov_bitly_data2012-03-16-1331923249.txt'

In [3]:
records = [json.loads(line) for line in open(path)]

FileNotFoundError: [Errno 2] No such file or directory: 'ch-2/usagov_bitly_data2012-03-16-1331923249.txt'

In [4]:
time_zones = [rec['tz'] for rec in records]

NameError: name 'records' is not defined

In [5]:
import numpy as np

In [6]:
data = np.random.randn(2, 3)

In [7]:
data

array([[ 0.21726084, -0.83251791,  0.73149261],
       [-0.22546186, -0.3198696 ,  1.39598796]])

In [8]:
data*10

array([[ 2.17260837, -8.32517912,  7.3149261 ],
       [-2.25461859, -3.19869596, 13.95987955]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
data1 = [6, 7.5, 8, 0, 1]

In [12]:
data1

[6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
arr2.ndim

2

In [22]:
arr2.shape

(2, 4)

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr2.dtype

dtype('int32')

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.zeros((3, 6))+1

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [28]:
np.empty((2, 3, 2))

array([[[1.12797659e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11256817e-306, 2.92966904e-033]],

       [[6.19895796e-091, 5.49167908e+174],
        [3.55095694e-062, 9.77380719e+165],
        [3.99910963e+252, 2.54740556e-052]]])

In [29]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [31]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [32]:
arr1.dtype

dtype('float64')

In [34]:
arr2.dtype

dtype('int32')

In [35]:
arr = np.array([1,2,3,4,5])

In [36]:
arr.dtype

dtype('int32')

In [38]:
float_arr = arr.astype(np.float64)

In [39]:
float_arr.dtype

dtype('float64')

In [40]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [41]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [42]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [43]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [44]:
arr.dtype

dtype('float64')

In [45]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [46]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [47]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [48]:
int_array = np.arange(10)

In [49]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [50]:
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [51]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
empty_unit32 = np.empty(8, dtype='u4')

In [53]:
empty_unit32


array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [54]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [55]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [57]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [59]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [60]:
arr*0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [61]:
arr=np.arange(10)

In [62]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr[5]

5

In [64]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr[5:8]

array([5, 6, 7])

In [66]:
arr[5:8]

array([5, 6, 7])

In [67]:
arr[5:8] = 12

In [68]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [69]:
arr_slice = arr[5:8]

In [70]:
arr_slice[1] = 12345

In [71]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [72]:
arr_slice[:] = 64

In [73]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])