In [1]:
import pandas as pd
import numpy as np

In [2]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [3]:
arr2d[2]

array([7, 8, 9])

In [4]:
arr2d[0][2]

3

In [5]:
arr2d[0,2]

3

In [8]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

In [9]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
old_values = arr3d[0].copy()

In [12]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr3d[0] = 42

In [15]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr3d[0] = old_values

In [17]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
arr3d[1,0]

array([7, 8, 9])

In [19]:
arr[1:6]

NameError: name 'arr' is not defined

In [21]:
arr=np.arange(10)

In [22]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [23]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [26]:
arr2d[1, :2]

array([4, 5])

In [28]:
arr2d[2, :1]

array([7])

In [29]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [30]:
arr2d[:2, 1:] = 0

In [31]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [32]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [33]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [34]:
data = np.random.randn(7, 4)

In [35]:
data

array([[ 1.5968479 ,  0.81292487, -1.72324784, -0.07593962],
       [ 0.29826364, -0.97434738,  0.70593228, -0.00897417],
       [ 0.99820762,  0.49718634, -1.13716368, -0.70683849],
       [ 0.85278186,  0.02871336, -1.29054936, -0.34541259],
       [-0.07497527, -0.48991362, -0.66609511,  0.39458071],
       [ 3.21441496,  0.24665439,  0.05652889, -0.30927951],
       [-0.03812681, -1.22665242, -0.81553565,  1.18195162]])

In [36]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [37]:
data[names == 'Bob']

array([[ 1.5968479 ,  0.81292487, -1.72324784, -0.07593962],
       [ 0.85278186,  0.02871336, -1.29054936, -0.34541259]])

In [38]:
data[names == 'Bob', 2:]

array([[-1.72324784, -0.07593962],
       [-1.29054936, -0.34541259]])

In [39]:
data[names == 'Bob', 3]

array([-0.07593962, -0.34541259])

In [40]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [42]:
data[~(names == 'Bob')]

array([[ 0.29826364, -0.97434738,  0.70593228, -0.00897417],
       [ 0.99820762,  0.49718634, -1.13716368, -0.70683849],
       [-0.07497527, -0.48991362, -0.66609511,  0.39458071],
       [ 3.21441496,  0.24665439,  0.05652889, -0.30927951],
       [-0.03812681, -1.22665242, -0.81553565,  1.18195162]])

In [43]:
mask = (names == 'Bob') | (names == 'will')

In [44]:
mask

array([ True, False, False,  True, False, False, False])

In [45]:
data[mask]

array([[ 1.5968479 ,  0.81292487, -1.72324784, -0.07593962],
       [ 0.85278186,  0.02871336, -1.29054936, -0.34541259]])

In [46]:
data[data < 0] = 0

In [47]:
data

array([[1.5968479 , 0.81292487, 0.        , 0.        ],
       [0.29826364, 0.        , 0.70593228, 0.        ],
       [0.99820762, 0.49718634, 0.        , 0.        ],
       [0.85278186, 0.02871336, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.39458071],
       [3.21441496, 0.24665439, 0.05652889, 0.        ],
       [0.        , 0.        , 0.        , 1.18195162]])

In [48]:
data[names != 'Joe'] = 7

In [49]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.29826364, 0.        , 0.70593228, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [3.21441496, 0.24665439, 0.05652889, 0.        ],
       [0.        , 0.        , 0.        , 1.18195162]])